### ISSUE TITLE
☔ Issue: Remove Internet Explorer Support

### ISSUE THREAD

**Issue by Danielku15** [CoderLine/alphaTab#507]
The Internet Explorer is a dead browser and holds us back from using more modern technologies. This umbrella issue holds all details/steps that adress the removal of the IE support and some possible modernization steps thanks to that. The related [poll/discussion](https://github.com/CoderLine/alphaTab/discussions/460) showed most alphaTab integrators do not need IE support. 

- [x] ~~Upgrade to ES6 compilation #508~~
- [x] ~~Remove VB based binary loader #509~~
- [x] ~~Custom UTF Encoder/Decoder #509~~
- [x] ~~Reduce `.foreach` calls and replace them with `for of` loops #509~~
- [x] ~~Use dominant-baseline again for better center alignment #509~~
- [x] ~~Use [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) #510~~
- [x] ~~Use [Resize Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Resize_Observer_API) #511~~
- [x] Usage [Audio Worklets](https://developer.mozilla.org/en-US/docs/Web/API/AudioWorklet) #480
- [x] ~~Update website~~
